### ISSUE TITLE
manager-events stuck in past

### ISSUE THREAD

**Issue by wmaxfield** [MetaWatchOpenProjects/MWM-for-iOS-Gen1#1]
Events for January are showing up in today's list, (June).  Appears to be no ability to choose which event to start with.  Would like MWM to keep up with current date for that list.

**Comment by metawatchclient** [comment]
Could you check the end date of the event stuck in MWM. The MWM will display the event until the end date passed.

**Comment by wmaxfield** [comment]
The event is a one-day event with a repeat of yearly, end point never.  It is a birthday.

  That needs to be handled, somehow.  I'm sure others have the same kind of repeating event.

**Comment by metawatchclient** [comment]
OK. I have yearly event also in may calendar...but it does not stuck there. I will see what I can do about this...

**Comment by metawatchclient** [comment]
done.
calendar widget will not only display your upcoming event, an event with a passed start date will be excluded from upcoming events.
