### ISSUE TITLE
weather widget find nothing in baden-württemberg/germany

### ISSUE THREAD

**Issue by mash-m** [MetaWatchOpenProjects/MWM-for-iOS-Gen1#11]
hi, the weather widget finds notinh in baden-wuerttemberg-germany like heidelberg, stuttgart, karlsruhe and so on.

**Comment by mash-m** [comment]
maybe the MWWeatherMonitor.h line 60 is the problem:
NSUTF8StringEncoding

maybe NSASCIIStringEncoding is the sollution, i will test it.

**Comment by metawatchclient** [comment]
Ues this:
I will push it later, but this fixed the issue.

```
NSString *stringReply = [[NSString alloc] initWithData:connData encoding:NSISOLatin1StringEncoding];
NSLog(@"%@", stringReply);

NSXMLParser *parser = [[NSXMLParser alloc] initWithData:[stringReply dataUsingEncoding:NSUTF8StringEncoding]];
[parser setShouldProcessNamespaces:YES];
[parser setShouldResolveExternalEntities:YES];
[parser setShouldReportNamespacePrefixes:YES];
[parser setDelegate:self];
[parser parse];

[stringReply release];
[parser release];
```

**Comment by metawatchclient** [comment]
These are the headers if you are interested:

Cache-Control: no-cache, no-store, must-revalidate
Connection: close
Content-Type: text/xml; charset=ISO-8859-1
Date: Fri, 13 Jul 2012 10:09:41 GMT
Expires: Fri, 01 Jan 1990 00:00:00 GMT
Pragma: no-cache
Server: igfe
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block

**Comment by mash-m** [comment]
thank you

**Comment by mash-m** [comment]
hi, i testet the changes. works fine now, but the wather icons won´t change. i had no time to search for the error. markus
