### ISSUE TITLE
Newest version won't compile with iOS5

### ISSUE THREAD

**Issue by jamierytlewski** [MetaWatchOpenProjects/MWM-for-iOS-Gen1#17]
I can't get the newest version to compile. It seems as though some libraries (Address book) got added into the libwmanager, which we have no access to.

**Comment by metawatchclient** [comment]
I noticed that too... I will fix this. There will be a new MWM for iOS 6, so this MWM will now have a slower update cycle.

**Comment by chriscana** [comment]
Wont build.

**Comment by jamierytlewski** [comment]
So is this separate project going to be up anytime soon? I'd really like to take a look at it.
