### ISSUE TITLE
Watch disconnecting approximately every 15 seconds

### ISSUE THREAD

**Issue by jamierytlewski** [MetaWatchOpenProjects/MWM-for-iOS-Gen1#18]
Ever since updating to iOS6 and updating the MWM-for-iPhone my watch is disconnecting and reconnecting after approximately 15 seconds.

**Comment by calvindomenico** [comment]
I am seeing the same problem since updating to ios 6 as well

**Comment by jasondukes** [comment]
Here as well.

**Comment by rillout** [comment]
The same problem
