### ISSUE TITLE
Feature Ideas

### ISSUE THREAD

**Issue by mickilus** [MetaWatchOpenProjects/MWM-for-iOS-Gen1#19]
I'm not sure if this git is even getting looked at but....
- Music control should be able to do third party music apps (Spotify, Rdio, etc), the technology/code already exists, lots of bluetooth headsets have play/pause, skip/back, vol up/vol down.
- Instead of the middle left button going directly to music, it'd be cool if it went to like a secondary apps screen. It could be formatted just like the system config screen. Then you could include a timer, stopwatch, etc (all features that should be in a $200 watch anyway)

**Comment by metawatchclient** [comment]
Only headset can control third party music player... MWM cannot do that...

**Comment by mickilus** [comment]
What does that mean? The bluetooth profile is already being used...
