### ISSUE TITLE
Weather high / low

### ISSUE THREAD

**Issue by arseetoo** [MetaWatchOpenProjects/MWM-for-iOS-Gen1#3]
Hi there,

Great work so far.  Really happy with the app.  I look forward to going in and picking apart the code to learn from it.  Anyway... while the current temp always seems to be accurate, I notice that the weather highs and lows do not seem to be correct.  For instance, I live in Webster, NY and today we are due for record highs at 91 degrees F, and have lows about 66 degrees F.  However, the watch shows a High of 77 and a low of 55.  Any ideas?

Thanks,
Ron
ron@rc2photo.com

**Comment by arseetoo** [comment]
And... being new to this developement thing, I right-away installed iOS 6 yesterday, and now the MWM app will not connect with my watch.  Sometimes I'm so dumb!

**Comment by metawatchclient** [comment]
fiixed in next release.
