### ISSUE TITLE
Time on Watch Is 5 Seconds Behind iPhone

### ISSUE THREAD

**Issue by slprice** [MetaWatchOpenProjects/MWM-for-iOS-Gen1#5]
Displaying seconds on the MetaWatch and comparing to iPhone time shows the watch 5 seconds behind the phone.

MWM version 0.1.1 beta
MetaWatch BLE version 3.1.0, stack 2.0.0
iPhone 4S, iOS 5.1.1

**Comment by metawatchclient** [comment]
Because both of the displays show the realtime of each device... so there will be some deviations...
Manually change the time format when BLE command queue is empty, will give you a perfect synced time between watch and phone.

**Comment by metawatchclient** [comment]
now the time deviation has been reduced to 2 secs...
If you still think this is not enough, manually change a time setting, while the BLE queue is empty.

**Comment by slprice** [comment]
With 0.1.2 the time has still been seen to be behind by up to about 5 seconds, but also as little as 1. I would think that if it is possible to set the time accurately, then it should be done that way. As a consumer I would not buy a timepiece that was consistently off, if even by only a few seconds. As a developer it is a fun toy though.

**Comment by metawatchclient** [comment]
In our 0.1.3 version, there is an option to enable writewithouresponse. Enable that would decrease the gap by 3 secs...
