### ISSUE TITLE
Weather - works partially on French iPhone

### ISSUE THREAD

**Issue by thierryb** [MetaWatchOpenProjects/MWM-for-iOS-Gen1#8]
My iPhone is in French, calling google's web service return response in French. Like "Nuageux" instead of Cloudy.
The result is that the icon is not the right one.

**Comment by metawatchclient** [comment]
Please try our latest source... this should be fixed already.

**Comment by thierryb** [comment]
I recompiled latest source.
weather icon is not the right one:

2012-06-19 10:31:50.569 MWM[1550:907] Montreal, QC,Mostly Cloudy, 22, 28, 21
2012-06-19 10:31:50.571 MWM[1550:907] unknown weather:Mostly Cloudy

**Comment by metawatchclient** [comment]
I know... I need to collect a complete list of google weather conditions to fix this.
Thanks... It is fixed in latest source code.
